\documentclass[a4paper]{article}

\title{Permutation Results}
\author{Author}

\begin{document}
\SweaveOpts{concordance=TRUE}

<<echo=FALSE>>=
library(ggplot2)
source('/Library/WebServer/CGI-Executables/newPack/plotFunc.R')
source('/Library/WebServer/CGI-Executables/newPack/statFunc.R')
@


\setkeys{Gin}{width=1.0\textwidth} 
<<echo=TRUE,fig=TRUE,width=9,height=15>>= 
ggEnsHist(\Sexpr{ensObj})
@

\end{document}
